### ISSUE TITLE
Error during loading

### ISSUE THREAD

**Issue by joaoandredcruz** [JackyCZJ/Z370M-MORTAR-I7-9700K-M9PEG-CLOVER#1]
Hello, i have 
mortherbroad : MSI Mortar Z370M
CPU: intel i5 9600k
Disk : kingston a1000
Graphics: Intel UHD Graphics 630 & RX5700
Memory: Corsair DDR4 2600 MHz
OS: 10.15.6

I already added a serial number, but the loading crashes in 60% approximately, can u help me?

**Comment by JackyCZJ** [comment]
seems it could be the boot arg error , My config use   ```agdpmod=pikera -disablegfxfirmware``` to avoid r470 black screem , maybe you can lookup whatevergreen.kext and find some information for rx5700.
